tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
  - command: |
      pip install pyspark
  - command: |
      pip install pandas
ports:
  - port: 9090
    onOpen: open-browser
  - port: 9091
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
